stages:
  data_ingestion:
    cmd: python src/DetectAnalytics/pipeline/stage_01_data_ingestion.py
    deps:
      - src/DetectAnalytics/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/firstdata


  preparing_model:
    cmd: python src/DetectAnalytics/pipeline/stage_02_preparing_model.py
    deps:
      - src/DetectAnalytics/pipeline/stage_02_preparing_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
      - IMAGE_HEIGHT
      - IMAGE_WIDTH
      - SEQUENCE
      - CLASSES_LIST
    outs:
      - artifacts/preparing_model



  training:
    cmd: python src/DetectAnalytics/pipeline/stage_03_training.py
    deps:
      - src/DetectAnalytics/pipeline/stage_03_training.py
      - src/DetectAnalytics/components/prepare_callbacks.py
      - config/config.yaml
      - artifacts/data_ingestion/firstdata
      - artifacts/preparing_model
    params:
      - EPOCHS
      - BATCH_SIZE
    outs:
      - artifacts/training/model.h5


  

  evaluation:
    cmd: python src/DetectAnalytics/pipeline/stage_04_evaluation.py
    deps:
      - src/DetectAnalytics/pipeline/stage_04_evaluation.py
      - config/config.yaml
      - artifacts/data_ingestion/firstdata
      - artifacts/training/model.h5
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
    - scores.json:
        cache: false