AUGMENTATION: True
IMAGE_SIZE: [16, 64, 64, 3]
BATCH_SIZE: 8
INCLUDE_TOP: False
EPOCHS: 50
WEIGHTS: imagenet
LEARNING_RATE: 0.01
IMAGE_HEIGHT: 64
IMAGE_WIDTH: 64
SEQUENCE: 16
CLASSES: 2
CLASSES_LIST: ["firstdata/nofight", "firstdata/fight"]
